Model change
CarryVan/Real_Time_Virtual_Home_Trainer pull request #2
Opened 2021-12-15 07:32 UTC by Sungijnwoo

sklearn model change

2021-12-15 08:09 UTC, Younghoon-Lee requested changes

2021-12-15 08:09 UTC, Younghoon-Lee commented on server.py
> +                ssl_keyfile="./localhost+2-key.pem",
여기 ssl_keyfile, ssl_certfile 지워주셔도 될 것 같습니다.

2021-12-15 08:11 UTC, Younghoon-Lee commented
그리고 필요 없는 출력문 지워주시면 좋을 것 같습니다.

2021-12-16 01:57 UTC, Younghoon-Lee reviewed
main 그대로 남아있는것 같네요

2021-12-16 02:16 UTC, Younghoon-Lee approved these changes

2021-12-17 08:18 UTC, nagyaong approved these changes

2021-12-17 08:18 UTC, hellojun12 approved these changes

2021-12-17 08:19 UTC, merged